package com.smartlogix.mapper;

import com.smartlogix.domain.entity.Order;
import com.smartlogix.dto.OrderRequestDTO;
import com.smartlogix.dto.OrderResponseDTO;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper that converts between {@link Order} JPA entities and their corresponding DTOs.
 * <p>
 * Using MapStruct ensures type-safe, compile-time verified mapping with zero reflection overhead
 * at runtime. The generated implementation is registered as a Spring bean via
 * {@code componentModel = "spring"}.
 * </p>
 */
@Mapper(componentModel = "spring")
public interface OrderMapper {

    /**
     * Converts an {@link Order} entity to an {@link OrderResponseDTO} suitable for API responses.
     * <p>
     * The {@code tenant.id} nested field is flattened to the top-level {@code tenantId} property
     * in the DTO so that clients do not need to navigate a nested object.
     * </p>
     *
     * @param order the persisted order entity
     * @return a populated {@link OrderResponseDTO}
     */
    @Mapping(source = "tenant.id", target = "tenantId")
    OrderResponseDTO toResponseDTO(Order order);

    /**
     * Converts an {@link OrderRequestDTO} (inbound creation payload) to an {@link Order} entity.
     * <p>
     * Several fields that are managed by the service layer are intentionally ignored here
     * and must be set after mapping:
     * <ul>
     *   <li>{@code id} — generated by the database</li>
     *   <li>{@code tenant} — resolved from {@link com.smartlogix.security.TenantContext}</li>
     *   <li>{@code createdBy} — resolved from the security context</li>
     *   <li>{@code status} — always initialized to {@code PENDING} by the service</li>
     *   <li>{@code createdAt} / {@code updatedAt} — managed by JPA auditing</li>
     * </ul>
     * </p>
     *
     * @param dto the inbound order creation payload
     * @return a partially populated {@link Order} entity (service layer fills the ignored fields)
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "tenant", ignore = true)
    @Mapping(target = "createdBy", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Order toEntity(OrderRequestDTO dto);
}
